export default [
  ["introduction", "Introduction to React Native and Expo"],
  ["styling", "Styling Components"],
  ["pressables", "Working with Pressables"],
  ["user_input", "Collecting User Input"],
  ["lists", "Working with Lists"],
  ["screens_and_stacks", "Navigating with Screens and Stacks"],
  ["navigation", "Creating Multi-Screen Apps"],
  ["overlays", "Working with Overlays"],
  ["animations", "Animating Components"],
  ["complex_animations", "Creating Complex Animations"],
  ["gestures", "Working with Gestures"],
  ["links", "Linking and Deep Linking"],
  ["data_storage", "Storing Data"],
  ["security", "Authorising Users and Securing Data"],
  ["accessibility", "Writing Accessible Native Apps"],
  ["debugging", "Debugging React Native Apps"],
  ["performance", "Measuring, Debugging, and Improving Performance"],
] as const;
